### ISSUE TITLE
Fails to build with Rust > 1.79

### ISSUE THREAD

**Issue by 0323pin** [Byron/crates-io-cli-rs#12]
@Byron Hi, would it be possible to bump `time` and fix the build with Rust-1.80?

Right now, release cannot be built as it fails with:
```
error[E0282]: type annotations needed for `Box<_>`
  --> /pbulk/work/www/crates-io-cli/work/vendor/time-0.3.30/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++
```

Thanks!
`time` >= 0.3.36 would solve this.

**Comment by Byron** [comment]
I think I see what the problem is. With `cargo install crates-io-cli` it fails with:

```
error[E0283]: type annotations needed
   --> /Users/byron/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gix-url-0.13.3/src/lib.rs:122:54
    |
122 |             let path = gix_path::from_bstr(self.path.as_ref());
    |                                                      ^^^^^^
    |
    = note: multiple `impl`s satisfying `BString: AsRef<_>` found in the `bstr` crate:
            - impl AsRef<BStr> for BString;
            - impl AsRef<[u8]> for BString;
help: try using a fully qualified path to specify the expected types
    |
122 |             let path = gix_path::from_bstr(<BString as AsRef<T>>::as_ref(&self.path));
    |                                            +++++++++++++++++++++++++++++++         ~

error[E0283]: type annotations needed
   --> /Users/byron/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gix-url-0.13.3/src/lib.rs:122:24
    |
122 |             let path = gix_path::from_bstr(self.path.as_ref());
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type for reference `&_`
    |
    = note: multiple `impl`s satisfying `Cow<'_, BStr>: From<&_>` found in the `bstr` crate:
            - impl<'a> From<&'a BStr> for Cow<'a, BStr>;
            - impl<'a> From<&'a BString> for Cow<'a, BStr>;
    = note: required for `&_` to implement `Into<Cow<'_, BStr>>`
note: required by a bound in `from_bstr`
   --> /Users/byron/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gix-path-0.7.3/src/convert.rs:116:34
    |
116 | pub fn from_bstr<'a>(input: impl Into<Cow<'a, BStr>>) -> Cow<'a, Path> {
    |                                  ^^^^^^^^^^^^^^^^^^^ required by this bound in `from_bstr`

For more information about this error, try `rustc --explain E0283`.
error: could not compile `gix-url` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `crates-io-cli v4.0.2`, intermediate artifacts can be found at `/var/folders/x7/jgy95vjs3v3ffszwn0wg0gz80000gn/T/cargo-installporcMb`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

And without `cargo install --locked crates-io-cli` it fails with the issue described here. Thus there is no way to install it right now.

**Comment by Byron** [comment]
A new point-release was just created and `crates-io-cli` can be installed once again.

https://github.com/Byron/crates-io-cli/releases/tag/v4.0.3

**Comment by 0323pin** [comment]
Wow, that was quick. Thank you!

**Comment by 0323pin** [comment]
@Byron Not as fast as you but, [merged](https://mail-index.netbsd.org/pkgsrc-changes/2024/10/17/msg308890.html) now
